---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedNamespacePlacement
metadata:
  name: federation-test
spec:
  clusterNames:
  - raffa1
  - raffa2
---    
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: test-deployment
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx
            name: nginx
---   
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeploymentPlacement
metadata:
  name: test-deployment
spec:
  clusterNames:
  - raffa1
  - raffa2
---    
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: test-service
spec:
  template:
    spec:
      selector:
        app: nginx
      type: NodePort
      ports:
        - name: http
          port: 80

---  
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: test-service
spec:
  clusterNames:
  - raffa1
  - raffa2                          