---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedcertificates.certmanager.k8s.io
spec:
  group: certmanager.k8s.io
  names:
    kind: FederatedCertificate
    plural: federatedcertificates
  scope: Namespaced
  version: v1alpha1
---
# placement type
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedcertificateplacements.certmanager.k8s.io
spec:
  group: certmanager.k8s.io
  names:
    kind: FederatedCertificatePlacement
    plural: federatedcertificateplacements
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterNames:
              items:
                type: string
              type: array
          type: object
        status:
          type: object
  version: v1alpha1
---
# override type
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedcertificateoverrides.certmanager.k8s.io
spec:
  group: certmanager.k8s.io
  names:
    kind: FederatedCertificateOverride
    plural: federatedcertificateoverrides
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            overrides:
              type: array
              items:
                properties:
                  clusterName:
                    type: string
                  data:
                    type: string
        status:
          type: object
  version: v1alpha1
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: certificates.certmanager.k8s.io
  namespace: federation-system
spec:
  target:
    version: v1alpha1
    kind: Certificate
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: certmanager.k8s.io
    version: v1alpha1
    kind: FederatedCertificate
  placement:
    kind: FederatedCertificatePlacement
  override:
    kind: FederatedCertificateOverride
  overridePath:
   - spec.dnsNames  