{{- if not .Values.limitedScope }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.4
  name: federation-role
rules:
- apiGroups:
  - core.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - multiclusterdns.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - scheduling.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
{{- end }}
