---  

- name: login
  command: oc login --username={{ cluster.username }} --password={{ cluster.password }} --server={{ cluster.url }} --insecure-skip-tls-verify=true
  
- name: get current context
  command: oc config current-context
  register: context

- name: get cluster context
  shell: oc config get-contexts {{ cluster.name }} --no-headers | wc -l
  register: lines

- name: delete previous cluster context
  command: oc config delete-context {{ cluster.name }}
  when: lines.stdout == '1'

- name: rename context
  command: oc config rename-context {{ context.stdout }} {{ cluster.name }}     
    
- name: Add Context to Clusters
  set_fact:
    tmp_cluster: "{{ [ (clusters | selectattr('name', 'match', cluster.name) | list | combine([{'context': cluster.name}]))] }}"       
  
- name: Update Clusters
  set_fact:
    clusters: "{{ clusters | rejectattr('name', 'match', cluster['name']) | list }} + {{ tmp_cluster }}" 