---
- name: login to the clusters
  include_tasks: authenticate.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster

- name: deploy federation control
  include_tasks: deploy-federation-control-plane.yaml
  with_items: "{{ clusters | selectattr('federation_control_plane') | list }}"
  loop_control:
    loop_var: cluster    