- name: remove federated objects
  shell: oc --context {{ cluster.context }} delete federatedtypeconfig --all -n federation-system
  register: del_result
#  failed_when: del_result.rc > 0 and del_result

- name: wait for federated object to be removed
  shell: oc --context {{ cluster.context }} get federatedtypeconfig -n federation-system 
  register: get_result
  until: get_result.stdout != "No resources found."
  retries: 10
  delay: 10 
    

- name: delete kube-multicluster-public namespace
  command: oc --context {{ cluster.context }} delete ns kube-multicluster-public --ignore-not-found=true
